[2025-07-22T15:00:01.625+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T15:00:01.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_pipeline.run_spark_job_container scheduled__2025-07-22T14:45:00+00:00 [queued]>
[2025-07-22T15:00:01.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_pipeline.run_spark_job_container scheduled__2025-07-22T14:45:00+00:00 [queued]>
[2025-07-22T15:00:01.669+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-22T15:00:01.697+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_spark_job_container> on 2025-07-22 14:45:00+00:00
[2025-07-22T15:00:01.705+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-22T15:00:01.707+0000] {standard_task_runner.py:63} INFO - Started process 87 to run task
[2025-07-22T15:00:01.707+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_data_pipeline', 'run_spark_job_container', 'scheduled__2025-07-22T14:45:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/flight_pipeline_dag.py', '--cfg-path', '/tmp/tmpqor74rz4']
[2025-07-22T15:00:01.709+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask run_spark_job_container
[2025-07-22T15:00:01.776+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_data_pipeline.run_spark_job_container scheduled__2025-07-22T14:45:00+00:00 [running]> on host e240c202458b
[2025-07-22T15:00:01.874+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_data_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_job_container' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T14:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-22T14:45:00+00:00'
[2025-07-22T15:00:01.877+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T15:00:01.899+0000] {docker.py:366} INFO - Starting docker container from image realtime-flight-pipeline/spark-job:0.1
[2025-07-22T15:00:01.904+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-07-22T15:00:02.205+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:00:02.20 [0m[38;5;2mINFO [0m ==>
[2025-07-22T15:00:02.206+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:00:02.20 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-07-22T15:00:02.207+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:00:02.20 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-07-22T15:00:02.209+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:00:02.20 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-07-22T15:00:02.210+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:00:02.21 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[2025-07-22T15:00:02.212+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m15:00:02.21 [0m[38;5;2mINFO [0m ==>
[2025-07-22T15:00:02.223+0000] {docker.py:436} INFO - 
[2025-07-22T15:00:04.826+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SparkContext: Running Spark version 3.5.1
[2025-07-22T15:00:04.828+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-07-22T15:00:04.829+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SparkContext: Java version 17.0.12
[2025-07-22T15:00:04.852+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO ResourceUtils: ==============================================================
[2025-07-22T15:00:04.853+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-07-22T15:00:04.854+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO ResourceUtils: ==============================================================
[2025-07-22T15:00:04.854+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SparkContext: Submitted application: FlightDataProcessing
[2025-07-22T15:00:04.871+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-07-22T15:00:04.879+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO ResourceProfile: Limiting resource is cpu
[2025-07-22T15:00:04.880+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-07-22T15:00:04.917+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SecurityManager: Changing view acls to: spark
[2025-07-22T15:00:04.917+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SecurityManager: Changing modify acls to: spark
[2025-07-22T15:00:04.918+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SecurityManager: Changing view acls groups to:
[2025-07-22T15:00:04.918+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SecurityManager: Changing modify acls groups to:
[2025-07-22T15:00:04.918+0000] {docker.py:436} INFO - 25/07/22 15:00:04 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: spark; groups with view permissions: EMPTY; users with modify permissions: spark; groups with modify permissions: EMPTY
[2025-07-22T15:00:04.969+0000] {docker.py:436} INFO - 25/07/22 15:00:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-07-22T15:00:05.209+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO Utils: Successfully started service 'sparkDriver' on port 44967.
[2025-07-22T15:00:05.234+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO SparkEnv: Registering MapOutputTracker
[2025-07-22T15:00:05.268+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO SparkEnv: Registering BlockManagerMaster
[2025-07-22T15:00:05.284+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-07-22T15:00:05.284+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-07-22T15:00:05.290+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-07-22T15:00:05.307+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-10f3512a-2600-4f14-941a-4f68cec748d9
[2025-07-22T15:00:05.320+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-07-22T15:00:05.337+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-07-22T15:00:05.443+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-07-22T15:00:05.497+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-07-22T15:00:05.614+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO Executor: Starting executor ID driver on host 24ac5be99a2a
[2025-07-22T15:00:05.615+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO Executor: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-07-22T15:00:05.616+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO Executor: Java version 17.0.12
[2025-07-22T15:00:05.625+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-07-22T15:00:05.626+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@25e00935 for default.
[2025-07-22T15:00:05.648+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40957.
[2025-07-22T15:00:05.648+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO NettyBlockTransferService: Server created on 24ac5be99a2a:40957
[2025-07-22T15:00:05.650+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-07-22T15:00:05.656+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 24ac5be99a2a, 40957, None)
[2025-07-22T15:00:05.660+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO BlockManagerMasterEndpoint: Registering block manager 24ac5be99a2a:40957 with 434.4 MiB RAM, BlockManagerId(driver, 24ac5be99a2a, 40957, None)
[2025-07-22T15:00:05.662+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 24ac5be99a2a, 40957, None)
[2025-07-22T15:00:05.664+0000] {docker.py:436} INFO - 25/07/22 15:00:05 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 24ac5be99a2a, 40957, None)
[2025-07-22T15:00:05.949+0000] {docker.py:436} INFO - Sessão Spark criada com sucesso!
[2025-07-22T15:00:07.714+0000] {docker.py:436} INFO - Traceback (most recent call last):
  File "/app/process_flights.py", line 81, in <module>
    main()
[2025-07-22T15:00:07.715+0000] {docker.py:436} INFO - File "/app/process_flights.py", line 59, in main
[2025-07-22T15:00:07.715+0000] {docker.py:436} INFO - flights_df = spark.createDataFrame(flight_list, schema=schema)
[2025-07-22T15:00:07.716+0000] {docker.py:436} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1443, in createDataFrame
[2025-07-22T15:00:07.716+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1485, in _create_dataframe
  File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1090, in _createFromLocal
[2025-07-22T15:00:07.716+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1459, in prepare
[2025-07-22T15:00:07.717+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2187, in verify
[2025-07-22T15:00:07.717+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2160, in verify_struct
[2025-07-22T15:00:07.717+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2187, in verify
[2025-07-22T15:00:07.717+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2181, in verify_default
[2025-07-22T15:00:07.718+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2006, in verify_acceptable_types
[2025-07-22T15:00:07.718+0000] {docker.py:436} INFO - pyspark.errors.exceptions.base.PySparkTypeError: [CANNOT_ACCEPT_OBJECT_IN_TYPE] `DoubleType()` can not accept object `0` in type `int`.
[2025-07-22T15:00:07.770+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO SparkContext: Invoking stop() from shutdown hook
[2025-07-22T15:00:07.770+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-07-22T15:00:07.778+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO SparkUI: Stopped Spark web UI at http://24ac5be99a2a:4040
[2025-07-22T15:00:07.787+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-07-22T15:00:07.796+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO MemoryStore: MemoryStore cleared
[2025-07-22T15:00:07.797+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO BlockManager: BlockManager stopped
[2025-07-22T15:00:07.801+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-07-22T15:00:07.802+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-07-22T15:00:07.809+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO SparkContext: Successfully stopped SparkContext
[2025-07-22T15:00:07.810+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO ShutdownHookManager: Shutdown hook called
[2025-07-22T15:00:07.811+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-a4183d7e-542c-4cc5-a1b9-ab56b9f0c282
[2025-07-22T15:00:07.813+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-d1fa1c2b-beb7-4440-810e-94371371dc73
[2025-07-22T15:00:07.816+0000] {docker.py:436} INFO - 25/07/22 15:00:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-a4183d7e-542c-4cc5-a1b9-ab56b9f0c282/pyspark-419b4a7d-b05f-4680-b8f7-ebbb001fb9f2
[2025-07-22T15:00:08.200+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T15:00:08.209+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.49/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.49/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpva50c3wr")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 380, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-22T15:00:08.214+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flight_data_pipeline, task_id=run_spark_job_container, run_id=scheduled__2025-07-22T14:45:00+00:00, execution_date=20250722T144500, start_date=20250722T150001, end_date=20250722T150008
[2025-07-22T15:00:08.225+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task run_spark_job_container (Docker container failed: {'StatusCode': 1}; 87)
[2025-07-22T15:00:08.261+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-22T15:00:08.275+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T15:00:08.277+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
