[2025-07-22T14:59:00.519+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T14:59:00.540+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_pipeline.run_spark_job_container manual__2025-07-22T14:58:57.273715+00:00 [queued]>
[2025-07-22T14:59:00.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_pipeline.run_spark_job_container manual__2025-07-22T14:58:57.273715+00:00 [queued]>
[2025-07-22T14:59:00.547+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-22T14:59:00.560+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_spark_job_container> on 2025-07-22 14:58:57.273715+00:00
[2025-07-22T14:59:00.566+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-22T14:59:00.568+0000] {standard_task_runner.py:63} INFO - Started process 70 to run task
[2025-07-22T14:59:00.568+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_data_pipeline', 'run_spark_job_container', 'manual__2025-07-22T14:58:57.273715+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/flight_pipeline_dag.py', '--cfg-path', '/tmp/tmpoxwl73er']
[2025-07-22T14:59:00.570+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask run_spark_job_container
[2025-07-22T14:59:00.613+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_data_pipeline.run_spark_job_container manual__2025-07-22T14:58:57.273715+00:00 [running]> on host e240c202458b
[2025-07-22T14:59:00.690+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_data_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_job_container' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T14:58:57.273715+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T14:58:57.273715+00:00'
[2025-07-22T14:59:00.694+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T14:59:00.719+0000] {docker.py:366} INFO - Starting docker container from image realtime-flight-pipeline/spark-job:0.1
[2025-07-22T14:59:00.723+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-07-22T14:59:01.093+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m14:59:01.09 [0m[38;5;2mINFO [0m ==>
[2025-07-22T14:59:01.095+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m14:59:01.09 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-07-22T14:59:01.096+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m14:59:01.09 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-07-22T14:59:01.097+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m14:59:01.09 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-07-22T14:59:01.098+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m14:59:01.09 [0m[38;5;2mINFO [0m ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit [1mhttps://bitnami.com/enterprise[0m
[2025-07-22T14:59:01.100+0000] {docker.py:436} INFO - [38;5;6mspark [38;5;5m14:59:01.09 [0m[38;5;2mINFO [0m ==>
[2025-07-22T14:59:01.117+0000] {docker.py:436} INFO - 
[2025-07-22T14:59:04.591+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SparkContext: Running Spark version 3.5.1
[2025-07-22T14:59:04.593+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-07-22T14:59:04.594+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SparkContext: Java version 17.0.12
[2025-07-22T14:59:04.622+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO ResourceUtils: ==============================================================
[2025-07-22T14:59:04.623+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-07-22T14:59:04.623+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO ResourceUtils: ==============================================================
[2025-07-22T14:59:04.624+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SparkContext: Submitted application: FlightDataProcessing
[2025-07-22T14:59:04.643+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-07-22T14:59:04.651+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO ResourceProfile: Limiting resource is cpu
[2025-07-22T14:59:04.651+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-07-22T14:59:04.705+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SecurityManager: Changing view acls to: spark
[2025-07-22T14:59:04.705+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SecurityManager: Changing modify acls to: spark
[2025-07-22T14:59:04.706+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SecurityManager: Changing view acls groups to:
[2025-07-22T14:59:04.706+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SecurityManager: Changing modify acls groups to:
[2025-07-22T14:59:04.706+0000] {docker.py:436} INFO - 25/07/22 14:59:04 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: spark; groups with view permissions: EMPTY; users with modify permissions: spark; groups with modify permissions: EMPTY
[2025-07-22T14:59:04.770+0000] {docker.py:436} INFO - 25/07/22 14:59:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-07-22T14:59:05.024+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO Utils: Successfully started service 'sparkDriver' on port 35551.
[2025-07-22T14:59:05.056+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO SparkEnv: Registering MapOutputTracker
[2025-07-22T14:59:05.090+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO SparkEnv: Registering BlockManagerMaster
[2025-07-22T14:59:05.106+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-07-22T14:59:05.107+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-07-22T14:59:05.110+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-07-22T14:59:05.132+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-4a03f75c-1ac7-444d-aed2-11383f99cd64
[2025-07-22T14:59:05.144+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-07-22T14:59:05.158+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-07-22T14:59:05.279+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-07-22T14:59:05.336+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-07-22T14:59:05.432+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO Executor: Starting executor ID driver on host c0a8b86a7959
[2025-07-22T14:59:05.433+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO Executor: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-07-22T14:59:05.433+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO Executor: Java version 17.0.12
[2025-07-22T14:59:05.439+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-07-22T14:59:05.440+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@7c86aa67 for default.
[2025-07-22T14:59:05.458+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45725.
25/07/22 14:59:05 INFO NettyBlockTransferService: Server created on c0a8b86a7959:45725
[2025-07-22T14:59:05.460+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-07-22T14:59:05.465+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, c0a8b86a7959, 45725, None)
[2025-07-22T14:59:05.468+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO BlockManagerMasterEndpoint: Registering block manager c0a8b86a7959:45725 with 434.4 MiB RAM, BlockManagerId(driver, c0a8b86a7959, 45725, None)
[2025-07-22T14:59:05.469+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, c0a8b86a7959, 45725, None)
[2025-07-22T14:59:05.471+0000] {docker.py:436} INFO - 25/07/22 14:59:05 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, c0a8b86a7959, 45725, None)
[2025-07-22T14:59:05.783+0000] {docker.py:436} INFO - Sessão Spark criada com sucesso!
[2025-07-22T14:59:07.477+0000] {docker.py:436} INFO - Traceback (most recent call last):
  File "/app/process_flights.py", line 81, in <module>
    main()
  File "/app/process_flights.py", line 59, in main
[2025-07-22T14:59:07.477+0000] {docker.py:436} INFO - flights_df = spark.createDataFrame(flight_list, schema=schema)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-22T14:59:07.478+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1443, in createDataFrame
[2025-07-22T14:59:07.478+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1485, in _create_dataframe
[2025-07-22T14:59:07.478+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1090, in _createFromLocal
[2025-07-22T14:59:07.479+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1459, in prepare
[2025-07-22T14:59:07.479+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2187, in verify
[2025-07-22T14:59:07.480+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2160, in verify_struct
[2025-07-22T14:59:07.480+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2187, in verify
[2025-07-22T14:59:07.480+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2181, in verify_default
[2025-07-22T14:59:07.480+0000] {docker.py:436} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 2006, in verify_acceptable_types
[2025-07-22T14:59:07.481+0000] {docker.py:436} INFO - pyspark.errors.exceptions.base.PySparkTypeError: [CANNOT_ACCEPT_OBJECT_IN_TYPE] `DoubleType()` can not accept object `0` in type `int`.
[2025-07-22T14:59:07.529+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO SparkContext: Invoking stop() from shutdown hook
[2025-07-22T14:59:07.529+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-07-22T14:59:07.538+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO SparkUI: Stopped Spark web UI at http://c0a8b86a7959:4040
[2025-07-22T14:59:07.547+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-07-22T14:59:07.557+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO MemoryStore: MemoryStore cleared
[2025-07-22T14:59:07.558+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO BlockManager: BlockManager stopped
[2025-07-22T14:59:07.562+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-07-22T14:59:07.564+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-07-22T14:59:07.571+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO SparkContext: Successfully stopped SparkContext
[2025-07-22T14:59:07.572+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO ShutdownHookManager: Shutdown hook called
[2025-07-22T14:59:07.572+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-45143a29-f68a-4965-ab41-2ce99366aca1
[2025-07-22T14:59:07.575+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-14d3ee77-4f7b-4290-9056-77f1d2b67deb/pyspark-fa70dba6-30d5-44b0-bf66-474d16e6478f
[2025-07-22T14:59:07.578+0000] {docker.py:436} INFO - 25/07/22 14:59:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-14d3ee77-4f7b-4290-9056-77f1d2b67deb
[2025-07-22T14:59:08.007+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T14:59:08.016+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.49/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 371, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 398, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.49/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpq8uvqpa3")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 509, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 380, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 444, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-22T14:59:08.021+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flight_data_pipeline, task_id=run_spark_job_container, run_id=manual__2025-07-22T14:58:57.273715+00:00, execution_date=20250722T145857, start_date=20250722T145900, end_date=20250722T145908
[2025-07-22T14:59:08.031+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task run_spark_job_container (Docker container failed: {'StatusCode': 1}; 70)
[2025-07-22T14:59:08.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-22T14:59:08.091+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T14:59:08.092+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
